/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestPartnerRouteImport } from './routes/request.partner'
import { Route as RequestCorporationRouteImport } from './routes/request.corporation'

const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestPartnerRoute = RequestPartnerRouteImport.update({
  id: '/request/partner',
  path: '/request/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestCorporationRoute = RequestCorporationRouteImport.update({
  id: '/request/corporation',
  path: '/request/corporation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/sandbox': typeof SandboxRoute
  '/request/corporation': typeof RequestCorporationRoute
  '/request/partner': typeof RequestPartnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/sandbox': typeof SandboxRoute
  '/request/corporation': typeof RequestCorporationRoute
  '/request/partner': typeof RequestPartnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/legal': typeof LegalRoute
  '/sandbox': typeof SandboxRoute
  '/request/corporation': typeof RequestCorporationRoute
  '/request/partner': typeof RequestPartnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/legal'
    | '/sandbox'
    | '/request/corporation'
    | '/request/partner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/legal'
    | '/sandbox'
    | '/request/corporation'
    | '/request/partner'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/legal'
    | '/sandbox'
    | '/request/corporation'
    | '/request/partner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LegalRoute: typeof LegalRoute
  SandboxRoute: typeof SandboxRoute
  RequestCorporationRoute: typeof RequestCorporationRoute
  RequestPartnerRoute: typeof RequestPartnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/partner': {
      id: '/request/partner'
      path: '/request/partner'
      fullPath: '/request/partner'
      preLoaderRoute: typeof RequestPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/corporation': {
      id: '/request/corporation'
      path: '/request/corporation'
      fullPath: '/request/corporation'
      preLoaderRoute: typeof RequestCorporationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LegalRoute: LegalRoute,
  SandboxRoute: SandboxRoute,
  RequestCorporationRoute: RequestCorporationRoute,
  RequestPartnerRoute: RequestPartnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
